import jsPDF from 'jspdf';
import { LoanApplication } from './types';

export function generateLoanPDF(
  application: Partial<LoanApplication>,
  clientName: string,
  clientEmail: string,
  dealDate: string
): jsPDF {
  const doc = new jsPDF();
  const pw = doc.internal.pageSize.getWidth();
  const margin = 14;
  const innerW = pw - margin * 2;
  let y = 12;

  const v = (val: unknown) => {
    if (val === null || val === undefined || val === '') return '';
    return String(val);
  };
  const cur = (val: unknown) => {
    if (val === null || val === undefined || val === '') return '';
    const n = Number(val);
    return isNaN(n) ? String(val) : '$' + n.toLocaleString();
  };
  const pct = (val: unknown) => {
    if (val === null || val === undefined || val === '') return '';
    return v(val) + '%';
  };

  // ── Helpers ──

  const sectionHeader = (title: string) => {
    checkPage(14);
    doc.setFillColor(35, 35, 35);
    doc.rect(margin, y, innerW, 7, 'F');
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255);
    doc.text(title.toUpperCase(), margin + 3, y + 5);
    doc.setTextColor(0);
    y += 7;
  };

  const fieldBox = (label: string, value: string, x: number, w: number, h = 12) => {
    // Border
    doc.setDrawColor(180);
    doc.setLineWidth(0.3);
    doc.rect(x, y, w, h);
    // Label
    doc.setFontSize(5.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    doc.text(label, x + 1.5, y + 3.5);
    // Value
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0);
    const trimmed = value || '';
    if (trimmed.length > 0) {
      doc.text(trimmed, x + 1.5, y + h - 2.5);
    }
    doc.setFont('helvetica', 'normal');
  };

  const fieldRow = (fields: [string, string][], h = 12) => {
    checkPage(h + 2);
    const w = innerW / fields.length;
    fields.forEach(([label, value], i) => {
      fieldBox(label, value, margin + w * i, w, h);
    });
    y += h;
  };

  const checkPage = (needed: number) => {
    if (y + needed > 280) {
      doc.addPage();
      y = 12;
    }
  };

  // ── Header ──
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Uniform Residential Loan Application', pw / 2, y, { align: 'center' });
  y += 5;
  doc.setFontSize(6.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(120);
  doc.text('Freddie Mac Form 65  |  Fannie Mae Form 1003', pw / 2, y, { align: 'center' });
  y += 3.5;
  doc.text(
    'Generated by Alina  |  ' +
      new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
    pw / 2,
    y,
    { align: 'center' }
  );
  doc.setTextColor(0);
  y += 6;

  // Thin line
  doc.setDrawColor(0);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pw - margin, y);
  y += 4;

  // ── Section I: Type of Mortgage and Terms of Loan ──
  sectionHeader('Section I — Type of Mortgage and Terms of Loan');

  fieldRow([
    ['Loan Amount', cur(application.loan_amount)],
    ['Interest Rate', pct(application.interest_rate)],
    ['No. of Months', v(application.term_months)],
  ]);

  fieldRow([
    ['Property Value / Appraised Value', cur(application.property_value)],
    ['Protective Equity', cur(application.protective_equity)],
    ['Combined Loan-to-Value (CLTV)', pct(application.cltv)],
  ]);

  y += 2;

  // ── Section II: Property Information ──
  sectionHeader('Section II — Property Information and Purpose of Loan');

  fieldRow([['Subject Property Address', v(application.property_address)]], 12);

  fieldRow([
    ['Property Type', v(application.property_type)],
    ['Square Footage', v(application.property_sqft)],
    ['Year Built', v(application.year_built)],
  ]);

  fieldRow([
    ['No. of Bedrooms', v(application.bedrooms)],
    ['No. of Bathrooms', v(application.bathrooms)],
    ['Lot Size (sq ft)', v(application.lot_size)],
  ]);

  y += 2;

  // ── Section III: Borrower Information ──
  sectionHeader('Section III — Borrower Information');

  fieldRow([
    ['Borrower Name', v(application.borrower_name || clientName)],
    ['Social Security Number', v(application.borrower_ssn)],
  ]);

  fieldRow([
    ['Date of Birth', v(application.borrower_dob)],
    ['Home Phone', v(application.borrower_phone)],
    ['Email', clientEmail],
  ]);

  y += 2;

  // ── Section IV: Employment Information ──
  sectionHeader('Section IV — Employment Information');

  fieldRow([
    ['Name & Address of Employer', v(application.employment)],
    ['Monthly Income', cur(application.employment_income)],
  ]);

  y += 2;

  // ── Section V: Assets and Liabilities ──
  sectionHeader('Section V — Monthly Income and Housing Expense');

  fieldRow([
    ['Liquid Assets (Cash, Savings, Investments)', cur(application.liquid_assets)],
    ['Rental Income', cur(application.rental_income)],
    ['Mid FICO Score', v(application.mid_fico)],
  ]);

  y += 2;

  // ── Section VI: 1st Trust Deed / Existing Mortgage ──
  sectionHeader('Section VI — Details of Existing Mortgage (1st Trust Deed)');

  fieldRow([
    ['Balance', cur(application.first_td_balance)],
    ['Monthly Payment', cur(application.first_td_monthly_payment)],
  ]);

  fieldRow([
    ['Interest Rate', pct(application.first_td_interest_rate)],
    ['Monthly HOA Fees', cur(application.monthly_hoa_fees)],
  ]);

  y += 2;

  // ── Missing Fields ──
  const missing = application.missing_fields || [];
  if (missing.length > 0) {
    checkPage(20);
    sectionHeader(`Incomplete — ${missing.length} Missing Field${missing.length > 1 ? 's' : ''}`);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(160, 100, 0);
    const labels = missing.map((f: string) => f.replace(/_/g, ' '));
    const text = labels.join('  •  ');
    const lines = doc.splitTextToSize(text, innerW - 6);
    doc.text(lines, margin + 3, y + 4);
    y += lines.length * 3.5 + 6;
    doc.setTextColor(0);
  }

  // ── Signature lines ──
  checkPage(30);
  y += 6;
  doc.setDrawColor(0);
  doc.setLineWidth(0.3);

  const sigW = (innerW - 20) / 2;
  // Borrower sig
  doc.line(margin, y + 12, margin + sigW, y + 12);
  doc.setFontSize(6);
  doc.setTextColor(100);
  doc.text("Borrower's Signature", margin, y + 16);
  doc.text('Date', margin + sigW - 15, y + 16);

  // Loan officer sig
  doc.line(margin + sigW + 20, y + 12, margin + sigW * 2 + 20, y + 12);
  doc.text("Loan Officer's Signature", margin + sigW + 20, y + 16);
  doc.text('Date', margin + sigW * 2 + 5, y + 16);

  doc.setTextColor(0);

  // ── Footer ──
  const ph = doc.internal.pageSize.getHeight();
  doc.setFontSize(5.5);
  doc.setTextColor(160);
  doc.text(
    'Uniform Residential Loan Application — Alina AI  |  This form is generated for review purposes. Verify all data before submission.',
    pw / 2,
    ph - 8,
    { align: 'center' }
  );
  doc.text('Freddie Mac Form 65  /  Fannie Mae Form 1003  (Rev. 2024)', pw / 2, ph - 5, {
    align: 'center',
  });

  return doc;
}
