import jsPDF from 'jspdf';
import { LoanApplication } from './types';

export function generateLoanPDF(
  application: Partial<LoanApplication>,
  clientName: string,
  clientEmail: string,
  dealDate: string
): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  const val = (v: unknown) => {
    if (v === null || v === undefined || v === '') return '—';
    return String(v);
  };

  const currency = (v: unknown) => {
    if (v === null || v === undefined || v === '') return '—';
    const num = Number(v);
    if (isNaN(num)) return String(v);
    return '$' + num.toLocaleString();
  };

  const pct = (v: unknown) => {
    if (v === null || v === undefined || v === '') return '—';
    return val(v) + '%';
  };

  // Header
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Loan Application', pageWidth / 2, y, { align: 'center' });
  y += 8;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(120);
  doc.text('Generated by Alina AI', pageWidth / 2, y, { align: 'center' });
  y += 5;
  doc.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), pageWidth / 2, y, { align: 'center' });
  doc.setTextColor(0);
  y += 10;

  // Line
  doc.setDrawColor(220);
  doc.line(20, y, pageWidth - 20, y);
  y += 8;

  // Client Info
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Client Information', 20, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);

  const addRow = (label: string, value: string, indent = 20) => {
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    doc.text(label, indent, y);
    doc.setTextColor(0);
    doc.setFont('helvetica', 'bold');
    doc.text(value, indent + 55, y);
    doc.setFont('helvetica', 'normal');
    y += 5.5;
  };

  addRow('Name:', val(application.borrower_name || clientName));
  addRow('Email:', clientEmail);
  addRow('Phone:', val(application.borrower_phone));
  addRow('SSN:', val(application.borrower_ssn));
  addRow('Date of Birth:', val(application.borrower_dob));
  addRow('FICO Score:', val(application.mid_fico));
  y += 4;

  // Section helper
  const addSection = (title: string, fields: [string, string][]) => {
    if (y > 260) {
      doc.addPage();
      y = 20;
    }
    doc.setDrawColor(220);
    doc.line(20, y, pageWidth - 20, y);
    y += 7;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0);
    doc.text(title, 20, y);
    y += 7;
    doc.setFontSize(9);

    // Two column layout
    const midX = pageWidth / 2 + 5;
    for (let i = 0; i < fields.length; i += 2) {
      const [l1, v1] = fields[i];
      addRow(l1, v1, 20);
      y -= 5.5; // go back up
      if (i + 1 < fields.length) {
        const [l2, v2] = fields[i + 1];
        addRow(l2, v2, midX);
      } else {
        y += 5.5;
      }
    }
    y += 4;
  };

  // Loan Details
  addSection('Loan Details', [
    ['Loan Amount:', currency(application.loan_amount)],
    ['Property Value:', currency(application.property_value)],
    ['Interest Rate:', pct(application.interest_rate)],
    ['Protective Equity:', currency(application.protective_equity)],
    ['Term:', application.term_months ? val(application.term_months) + ' months' : '—'],
    ['CLTV:', pct(application.cltv)],
  ]);

  // Subject Property
  addSection('Subject Property', [
    ['Address:', val(application.property_address)],
    ['Type:', val(application.property_type)],
    ['Sq Ft:', val(application.property_sqft)],
    ['Lot Size:', val(application.lot_size)],
    ['Bedrooms:', val(application.bedrooms)],
    ['Bathrooms:', val(application.bathrooms)],
    ['Year Built:', val(application.year_built)],
  ]);

  // 1st Trust Deed
  addSection('1st Trust Deed Details', [
    ['Balance:', currency(application.first_td_balance)],
    ['Monthly Payment:', currency(application.first_td_monthly_payment)],
    ['Interest Rate:', pct(application.first_td_interest_rate)],
    ['Monthly HOA:', currency(application.monthly_hoa_fees)],
  ]);

  // Borrower Financials
  addSection('Borrower Financials', [
    ['Employment:', val(application.employment)],
    ['Monthly Income:', currency(application.employment_income)],
    ['Liquid Assets:', currency(application.liquid_assets)],
    ['Rental Income:', currency(application.rental_income)],
  ]);

  // Missing fields warning
  const missing = application.missing_fields || [];
  if (missing.length > 0) {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }
    y += 4;
    doc.setDrawColor(220);
    doc.line(20, y, pageWidth - 20, y);
    y += 7;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(200, 120, 0);
    doc.text(`Missing Fields (${missing.length})`, 20, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(150, 100, 0);
    const missingText = missing.map((f: string) => f.replace(/_/g, ' ')).join(', ');
    const lines = doc.splitTextToSize(missingText, pageWidth - 40);
    doc.text(lines, 20, y);
    y += lines.length * 4;
  }

  // Footer
  doc.setTextColor(180);
  doc.setFontSize(7);
  doc.text(
    'This document was auto-generated by Alina AI Loan Processing. All data should be verified before submission.',
    pageWidth / 2,
    doc.internal.pageSize.getHeight() - 10,
    { align: 'center' }
  );

  return doc;
}
